/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/CzErrorPage/403.vue')['default']
    404: typeof import('./../src/components/CzErrorPage/404.vue')['default']
    ChatAside: typeof import('./../src/modules/chat/components/ChatAside.vue')['default']
    ChatContent: typeof import('./../src/modules/chat/components/ChatContent.vue')['default']
    ChatFeedback: typeof import('./../src/modules/chat/components/ChatFeedback.vue')['default']
    ChatFeedbackPop: typeof import('./../src/modules/chat/components/ChatFeedbackPop.vue')['default']
    ChatFooter: typeof import('./../src/modules/chat/components/ChatFooter.vue')['default']
    ChatHeader: typeof import('./../src/modules/chat/components/ChatHeader.vue')['default']
    ChatHistoryItem: typeof import('./../src/modules/chat/components/ChatHistoryItem.vue')['default']
    CzSvg: typeof import('./../src/components/CzSvg/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Error403: typeof import('./../src/components/CzErrorPage/error-403.vue')['default']
    Error404: typeof import('./../src/components/CzErrorPage/error-404.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZkSvg: typeof import('./../src/components/ZkSvg/index.vue')['default']
    ZkTyping: typeof import('./../src/components/ZkTyping/index.vue')['default']
  }
}
